language: java
before_install: umask 022
install: mvn clean install -Dmaven.test.skip=true -U
script: mvn test verify
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
notifications:
  irc: "irc.freenode.org#nodyn"
branches:
  only:
    - master
    - stat-debug

